apiVersion: apps/v1
kind: Deployment
metadata:
  name: shadcn-dashboard
spec:
  selector:
    matchLabels:
      app: shadcn-dashboard
  template:
    metadata:
      labels:
        app: shadcn-dashboard
    spec:
      containers:
      - name: shadcn-dashboard
        image: arjus100/shadcn-dashboard:dev
        imagePullPolicy: Always
      volumes:
        - name: dashboard-data
          persistentVolumeClaim:
            claimName: dashboard-data-pvc